### PR TITLE
make building UVAtlasTool optional in cmake

### PR DESCRIPTION
**Pull request by jasjuang**
This PR makes building UVAtlasTool optional in CMake, and it's defaulted to on. If we want to turn it off, we can do `cmake -DBUILD_TOOLS=OFF ..` while configuring CMake.

### CODE REVIEW

**Comment by walbourn** [comment]
Nice. Learning a lot about Cmake today :)

**Comment by jasjuang** [comment]
@walbourn Can you make a release? Even if it's just a minor release it will be helpful. I am going to coordinate with vcpkg to compile UVAtlas on Windows, they manage packages on a release basis and the main language they operate on is CMake.

**Comment by walbourn** [comment]
I'll do another release of all my libraries by the end of the week.

**Comment by jasjuang** [comment]
Actually let's not do the release just yet, we still need to add the `export` and `install` in CMakeLists to make it fully functional but it requires compilation. Let me find a Windows machine to add it.

**Pull request merged**
