### PR TITLE
Add CMake project and fix clang warnings

### PR DESCRIPTION
**Pull request by walbourn**
With VS 2019 Update 1 supporting the clang/LLVM toolset, I've formally added CMake files as well as addressed a number of clang warnings.

### CODE REVIEW

**Comment by jasjuang** [comment]
Thanks for making the effort to add CMake into this. Is this ready for testing and merge?

**Comment by walbourn** [comment]
I'm still working on cleaning up a bunch of warnings. I'll try to get back to this soon...

**Comment by walbourn** [comment]
For my other projects I've worked to get to ``/Wall /Wpedantic /Wextra`` clean, but that's taking a long while. I think I'll rescope to ``/W4`` for now and see if I can get it wrapped up in that form.

**Comment by walbourn** [comment]
Finished for now. Opened [this issue](https://github.com/microsoft/UVAtlas/issues/30) to track doing additional warnings cleanup in future.

**Pull request merged**
